# Generated by Django 2.2 on 2020-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attend',
            field=models.ManyToManyField(related_name='trips', to='firstApp.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
